name: KnoMol
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.10
  - hyperopt=0.2.7
  - numpy=1.22.1
  - pytorch=1.13.1  # More readily available version
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - rdkit=2022.03.2
  - networkx=2.8.6
  - pandas=1.4.4
  - pip
 # - pip:
 #   - torch-cluster==1.6.0
   # - torch-geometric==2.0.4
 #   - torch-geometric == 2.3.0
 #   - torch-scatter==2.0.9
 #   - torch-sparse==0.6.13
   # - torch-spline-conv==1.2.1
